providers = []

[phases.setup]
nixPkgs = ["php81", "php81Packages.composer", "chromium", "chromedriver", "supervisor"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "chromedriver --version",
    "chmod +x start.sh"
]

[start]
cmd = "supervisord -c supervisord.conf"
