providers = ["..."]

[phases.setup]
nixPkgs = ["...", "chromium", "chromedriver"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "chromedriver --version"
]

[start]
cmd = "chromedriver --port=9515 & php -S 0.0.0.0:$PORT index.php"
